export const STUDY_TYPES = {
  AUDIOGRAM: 'AUDIOGRAM',
  LOGOAUDIOGRAM: 'LOGOAUDIOGRAM',
  TIMPANOGRAM: 'TIMPANOGRAM',
  IMPEDANCIOMETER: 'IMPEDANCIOMETER',
  POTENCIAL: 'POTENCIAL',
  OTOEMISION: 'OTOEMISION',
};

export const a = '';
